In [2]:
import tensorflow as tf

In [5]:
#常量
a = tf.constant(2)
b = tf.constant(3)
c = a + b
#session使用完需要显示关闭，或者使用with tf.Session() as session:
sess = tf.Session()
print(sess.run(c))

5


In [6]:
#变量
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)
add = tf.add(a,b)
print(sess.run(add,feed_dict={a:2,b:3}))

5


In [9]:
matrix1 = tf.constant([[3.,3.]])
matrix2 = tf.constant([[2.],[3.]])
product = tf.matmul(matrix1,matrix2)
prod = tf.matmul(matrix2,matrix1)
print(sess.run(product))
print(sess.run(prod))

[[ 15.]]
[[ 6.  6.]
 [ 9.  9.]]


In [16]:
mat1 = tf.Variable(tf.random_normal([3,2]))
mat2 = tf.Variable(tf.random_normal([2,3]))
prod = tf.matmul(mat1,mat2)
m1 = [[1,3],[2,1],[0,5]]
m2 = [[3,2,1],[1,2,3]]
print(sess.run(prod,feed_dict={mat1:m1,mat2:m2}))

[[  6.   8.  10.]
 [  7.   6.   5.]
 [  5.  10.  15.]]
